{
 "title": "LinearSVC classifier",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prediction - true label",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "SWAT_classified",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_classified",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "description": "Displays incoming CDN stream",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "SWAT_classified",
     "query": "SELECT \"P101\", \"label\", \"prediction\", \"LIT401\" FROM \"SWAT_classified\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "P101" ], "type": "field" }
      ],
      [
       { "params": [ "label" ], "type": "field" }
      ],
      [
       { "params": [ "prediction" ], "type": "field" }
      ],
      [
       { "params": [ "AIT203" ], "type": "field" }
      ],
      [
       { "params": [ "FIT401" ], "type": "field" }
      ],
      [
       { "params": [ "MV303" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "True Label count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Label - $tag_label",
     "groupBy": [
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "SWAT_classified",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction - $tag_prediction",
     "groupBy": [
      { "params": [ "prediction" ], "type": "tag" }
     ],
     "measurement": "SWAT_classified",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "True Positives",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_classified\" WHERE (\"label\" = 1 AND \"prediction\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "False Negatives",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_classified\" WHERE (\"prediction\" = 0 AND \"label\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "False Positives",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_classified\" WHERE (\"label\" = 0 AND \"prediction\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Features ",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "SELECT \"LIT301\", \"PIT502\", \"AIT203\", \"DPIT301\", \"label\", \"prediction\" FROM \"SWAT_classified\" WHERE $timeFilter"
    }
   ]
  }
 ]
}