{
 "title": "Page Hinkley",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Predictions -AIT201",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Predictions - PIT502",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "PIT502" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Predictions - AIT203",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "AIT203" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Predictions - FIT101",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "FIT101" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction - label",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total data processed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_PageHinkley\" WHERE  $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "True Positives",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_PageHinkley\" WHERE (\"label\" = 1 AND \"prediction\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "False Negatives",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_PageHinkley\" WHERE (\"prediction\" = 0 AND \"label\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "False Positives",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"prediction\") FROM \"SWAT_PageHinkley\" WHERE (\"label\" = 0 AND \"prediction\" = 1) AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "True Label count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Label - $tag_label",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_PageHinkley",
     "query": "SELECT count(\"label\") FROM \"SWAT_PageHinkley\" WHERE $timeFilter GROUP BY \"label\"",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction - $tag_prediction",
     "query": "SELECT count(\"prediction\") FROM \"SWAT_PageHinkley\" WHERE $timeFilter GROUP BY \"prediction\" ORDER BY time DESC"
    }
   ]
  }
 ]
}