{
 "title": "dashboard_model_based_LR",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total data",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "True Positive",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Positive",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "query": "SELECT count(\"AIT201\")  FROM \"SWAT_MUL_sample\" WHERE (\"change\" = 1 AND \"label\" =1) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "change", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "True Negative",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Negative",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "query": "SELECT count(\"AIT201\")  FROM \"SWAT_MUL_sample\" WHERE (\"change\" = 0 AND \"label\" =0) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "change", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "False Positive",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "False Positive",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "query": "SELECT count(\"AIT201\")  FROM \"SWAT_MUL_sample\" WHERE (\"change\" = 1 AND \"label\" =0) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "change", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "False Negative",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "False Negative",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "query": "SELECT count(\"AIT201\")  FROM \"SWAT_MUL_sample\" WHERE (\"change\" = 0 AND \"label\" =1) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "change", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "AIT402 AIT401",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "AIT402" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "AIT401" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Label",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AIT504 PIT502",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "AIT504" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "PIT502" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "P101 FIT101 P202",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "P101" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "FIT101" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P201" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detected Change",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "change" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "P102 MV304",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_MUL_sample",
     "select": [
      [
       { "params": [ "MV304" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P102" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}