{
 "title": "LR_pred_dashboard",
 "time": { "from": "2022-12-02T15:13:32.479Z", "to": "2022-12-02T15:24:49.941Z" },
 "panels": [
  {
   "title": "Prediction vs Real label",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Prediction" ], "type": "alias" }
      ],
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Real Label" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AIT201 AIT503",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "AIT201",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "AIT201" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AIT201" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "AIT503",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "AIT503" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AIT203 AIT402",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "AIT203",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "AIT203" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AIT201" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "AIT402",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "AIT402" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Negative",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "query": "SELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 0 AND \"label\" = 0) AND $timeFilter;\n\n\n",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias111" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "prediction", "operator": "=", "value": "0.0" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "0.0" }
     ]
    },
    {
     "alias": "True Positive",
     "query": "\nSELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 1 AND \"label\" = 1) AND $timeFilter\n"
    },
    {
     "alias": "False Negative",
     "query": "SELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 0 AND \"label\" = 1) AND $timeFilter\n"
    },
    {
     "alias": "False Positive",
     "query": "SELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 1 AND \"label\" = 0) AND $timeFilter\n"
    }
   ]
  },
  {
   "title": "Total stream",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AIT203 AIT402",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "AIT401",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "select": [
      [
       { "params": [ "AIT401" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AIT201" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "True Positive Pred",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Positive",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "query": "SELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 1 AND \"label\" = 1) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "prediction", "operator": "=", "value": "0.0" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "0.0" }
     ]
    }
   ]
  },
  {
   "title": "True Negative Pred",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "True Negative",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SWAT_LR_PRED",
     "query": "SELECT count(\"prediction\") FROM \"autogen\".\"SWAT_LR_PRED\" WHERE (\"prediction\" = 0 AND \"label\" = 0) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "prediction", "operator": "=", "value": "0.0" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "0.0" }
     ]
    }
   ]
  }
 ]
}