{
 "title": "SWAT data CUSUM change detection",
 "tags": [
  "prediction",
  "label"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "label",
    "label": "label",
    "query": "select distinct label from CUSUM"
   },
   {
    "name": "prediction",
    "label": "prediction",
    "query": "select distinct Attack_Detected from CUSUM"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "# CUSUM change point detection for SWAT\n"
   }
  },
  {
   "title": "Predicted Attacks",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Attack $tag_prediction",
     "groupBy": [
      { "params": [ "prediction" ], "type": "tag" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"Attack_Detected\") FROM \"CUSUM\" WHERE $timeFilter GROUP BY prediction",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total attacks for most latest window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Count_sketch",
     "select": [
      [
       { "params": [ "count_sketch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Streaming Data points",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Streaming data points",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Total streaming points",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"label\") FROM \"CUSUM\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ground Truth Attacks",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Attack  $tag_label",
     "groupBy": [
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"Attack_Detected\") FROM \"CUSUM\" WHERE $timeFilter GROUP BY prediction",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attacks with PIT502 Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "PIT502",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "PIT502" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attacks with FIT101 Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "FIT101",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "FIT101" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction VS Ground Truth",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Correct Alarms (TP)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"prediction\") FROM \"CUSUM\" WHERE (\"prediction\" = 1 AND \"label\" = 1) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "prediction", "operator": "=", "value": "1.0" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1.0" }
     ]
    }
   ]
  },
  {
   "title": "False Alarms (FP)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"prediction\") FROM \"CUSUM\" WHERE (\"label\" = 0 AND \"prediction\" = 1) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "1.0" },
      { "condition": "AND", "key": "prediction", "operator": "=", "value": "1.0" }
     ]
    }
   ]
  },
  {
   "title": "Missed Attacks (FN)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "CUSUM",
     "query": "SELECT count(\"prediction\") FROM \"CUSUM\" WHERE (\"prediction\" = 0 AND \"label\" = 1) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "prediction", "operator": "=", "value": "0.0" },
      { "condition": "AND", "key": "label", "operator": "=", "value": "1.0" }
     ]
    }
   ]
  },
  {
   "title": "SWAT Data with predictions",
   "type": "table",
   "description": "Displays incoming SWAT stream and predictions",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "measurement": "CUSUM",
     "query": "SELECT \"LIT301\", \"AIT202\", \"AIT203\", \"AIT401\", \"label\", \"Attack_Detected\" FROM \"CUSUM\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "LIT301" ], "type": "field" }
      ],
      [
       { "params": [ "PIT502" ], "type": "field" }
      ],
      [
       { "params": [ "AIT203" ], "type": "field" }
      ],
      [
       { "params": [ "DPIT301" ], "type": "field" }
      ],
      [
       { "params": [ "label" ], "type": "field" }
      ],
      [
       { "params": [ "prediction" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}