{
 "title": "ADWIN",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "FIT101",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIT101 Predictions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "prediction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_FIT101",
       "select": [
        [
         { "params": [ "prediction" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_FIT101",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "True Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_FIT101\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FIT101 Stream",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "FIT101",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_FIT101",
       "select": [
        [
         { "params": [ "FIT101" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_FIT101",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "False Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_FIT101\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DPIT301",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPIT301 Predictions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "prediction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_DPIT301",
       "select": [
        [
         { "params": [ "prediction" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_DPIT301",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "True Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_DPIT301\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DPIT301 Stream",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
     "targets": [
      {
       "alias": "DPIT301",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_DPIT301",
       "select": [
        [
         { "params": [ "DPIT301" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_DPIT301",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "False Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_DPIT301\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "AIT203",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AIT203 Predictions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 3 },
     "targets": [
      {
       "alias": "prediction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_AIT203",
       "select": [
        [
         { "params": [ "prediction" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_AIT203",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "True Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_AIT203\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AIT203 Stream",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "AIT203",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_AIT203",
       "select": [
        [
         { "params": [ "AIT203" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "False Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_AIT203\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FIT101 & DPIT301 Combined",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIT101 & DPIT301 Predictions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "prediction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_combined",
       "select": [
        [
         { "params": [ "prediction" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ADWIN_combined",
       "select": [
        [
         { "params": [ "label" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "True Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_combined\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "False Alarms",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Kmeans",
       "query": "SELECT count(\"prediction\") FROM \"ADWIN_combined\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}