{
 "title": "Kmeans",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Vs Real Labels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "prediction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "real label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Real Attacks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "query": "SELECT count(\"label\") FROM \"Kmeans\" WHERE ( \"label\" = 1)  AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter Group by \"prediction\""
    },
    {
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 1 AND \"prediction\" = 0)  AND $timeFilter  group by \"prediction\"\n"
    }
   ]
  },
  {
   "title": "Total Correct Predicted Attacks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 1 AND \"prediction\" = 1)  AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total False Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 0 AND \"prediction\" = 1)  AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Missed Attacks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Kmeans",
     "query": "SELECT count(\"prediction\") FROM \"Kmeans\" WHERE ( \"label\" = 1 AND \"prediction\" = 0)  AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}